# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cars' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cars

  target 'CarsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarsUITests' do
    # Pods for testing
  end
  pod 'Kingfisher', '~> 4.0'
  pod 'KRProgressHUD'

end
